

module.exports =
  UiConstants: require './UiConstants'
  PayloadSources: {
    "SERVER_ACTION"
    "VIEW_ACTION"
  }
  ActionTypes: {
    "OPEN_SCHEDULE"
    "GET_SCHEDULES"
    "GET_SCHEDULES_SUCCESS"
    "GET_SCHEDULES_FAIL"
    "CREATE_SCHEDULE"
    "CREATE_SCHEDULE_SUCCESS"
    "CREATE_SCHEDULE_FAIL"
    "DELETE_SCHEDULE"
    "DELETE_SCHEDULE_SUCCESS"
    "DELETE_SCHEDULE_FAIL"
    "SAVE_SCHEDULE"
    "SAVE_SCHEDULE_SUCCESS"
    "SAVE_SCHEDULE_FAIL"
    "ADD_SECTION"
    "REMOVE_SECTION"
    "ADD_SECTION_PREVIEW"
    "REMOVE_SECTION_PREVIEW"
    "ADD_PERSONAL_EVENT"
    "REMOVE_PERSONAL_EVENT"
  }
